"""empty message

Revision ID: 0ca423e217bd
Revises: 9aee44e026a2
Create Date: 2019-10-07 11:08:23.786015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ca423e217bd'
down_revision = '9aee44e026a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printer', sa.Column('name', sa.String(length=180), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('printer', 'name')
    # ### end Alembic commands ###
