"""empty message

Revision ID: 9a8f1696264e
Revises: 10b2836c3f9d
Create Date: 2019-10-07 12:29:24.924172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a8f1696264e'
down_revision = '10b2836c3f9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printer', sa.Column('last_count', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('printer', 'last_count')
    # ### end Alembic commands ###
