"""empty message

Revision ID: 9aee44e026a2
Revises: 
Create Date: 2019-10-07 09:23:35.201083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aee44e026a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('printer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pat', sa.String(length=180), nullable=True),
    sa.Column('model', sa.String(length=180), nullable=True),
    sa.Column('ip', sa.String(length=180), nullable=True),
    sa.Column('crawler', sa.String(length=180), nullable=True),
    sa.Column('location', sa.String(length=180), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=True),
    sa.Column('user', sa.String(length=180), nullable=True),
    sa.Column('password', sa.String(length=180), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('printer')
    # ### end Alembic commands ###
